apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo@sha256:2acd7633fb72973922218369f366d4ad1f510ca2366362a3fbe01d47269bf8bd
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo@sha256:22dc4783356f64d8e1dd6d56a7850889dfa405cb084f1b1dd46a9fa505d68d96
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
