apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo
  labels:
    policy.sigstore.dev/include: "true"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/webthingy@sha256:fd9fa260758b64ca83634a00f3bebbbac91ead2f5dee7fd623fed7793b3febe9
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/mission-critical-service@sha256:7adafcbec442736ac3c9a63a3675cde68fb6b23d63652f9cf734b8590828553d
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coolest-serverless-app
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/coolest-serverless-app@sha256:24fba151c4dada76d442a54d36f0871681ae87bf62b07a03efe54647b29fdf5f
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
