apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/webthingy-15089cb2872e777201ad16570d8ac7d8@sha256:b934c1020d53342ac81731fd4af726bb15944b02c66f2d47728e5418eec72c1c
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/mission-critical-service-929a03fdbbfb2c2b621fbbabe2e0ac7b@sha256:442e54f0522134d6dea3b5324763eac1129f372e356149b1234878bbcac9597e
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
