apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo@sha256:3edf17d5600ba9baa179e71f5cb61bc0039a4174456080830affe0443b804860
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo@sha256:ab409d1a9c7dd8db83b2f83dfc6bdb820cae30056b496b1ca53b09010fdb3554
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
