apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo
  labels:
    policy.sigstore.dev/include: "true"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/webthingy@sha256:d7d30443d1020b5d3a0b84143b0138ca846bfb2e0e5b0b17da5b4cb1a4d868f2
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/mission-critical-service@sha256:ae8bb6895d8085cb0c087a870b2fdb0de6d48a18c90196a8ec8fb8877f572310
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coolest-serverless-app
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/coolest-serverless-app@sha256:c5f0ebe44c3166468221a067fef4fe09a2e453dda7488b848bb2abd963893d7a
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
