apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo
  labels:
    policy.sigstore.dev/include: "true"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/webthingy@sha256:b9a81090e6d23aa521a866ace82206c2c6eac10769ed5d687c477864b8910022
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/mission-critical-service@sha256:2ec9e4144f114a9fee33dc7b5248257c69fb90475f2778a62968108286a9e9dc
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coolest-serverless-app
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/coolest-serverless-app@sha256:801a28bd7e659af73e668d02da842c8a813497b95862f0070fd0e0f6c57744ba
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
