apiVersion: v1
kind: Namespace
metadata:
  name: sample-ko-monorepo
  labels:
    policy.sigstore.dev/include: "true"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webthingy
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/webthingy@sha256:0760ba45150e76632a427651dace069477dd735b4ff3ff232cde21fd0fb0012b
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mission-critical-service
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/mission-critical-service@sha256:6b6805e96740256840896b780b32015a63d5eacae05094a6a72df87cb20a8140
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coolest-serverless-app
  namespace: sample-ko-monorepo
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/bobymcbobs/sample-ko-monorepo/coolest-serverless-app@sha256:8835662592848ee6ad2a833d646ccd379a0de6a9c6d24df77c91310b98f43656
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
