name: build

on:
  push: {}
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sigstore/cosign-installer@main
      - run: |
          echo '${{ toJSON(github) }}' | jq .
      - id: go-version
        run: |
          echo "version=$(go list -f {{.GoVersion}} -m)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - uses: ko-build/setup-ko@v0.6
      - id: build-resolve
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        run: |
          export KO_DOCKER_REPO="${KO_DOCKER_REPO,,}"

          ko resolve --bare -f config/ > ./deploy/release.yaml
      - id: sign-image
        env:
          COSIGN_YES: "true"
          COSIGN_EXPERIMENTAL: "true"
        run: |
          for IMAGE in $(yq -N '. | select(.kind == "Service") | .spec.template.spec.containers[].image' deploy/release.yaml | xargs); do
            cosign sign --yes $IMAGE
          done
      - id: release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./deploy/release.yaml
