name: reusable golangci lint
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
      - canon
  pull_request: {}
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-golangci-lint.yml@main
    with:
      config: |
        linters:
          enable:
            - gosec
            - funlen
            - depguard
            - whitespace
