name: reusable golangci lint
on:
  workflow_dispatch: {}
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  pull_request: {}
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-golangci-lint.yml@main
