name: promote images

on:
  push:
    paths:
      - images/config.yaml
      - .github/workflows/image-promotion.yaml
      - .github/workflows/reusable-image-promotion.yaml
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  id-token: write
  packages: write

jobs:
  promote:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-image-promotion.yml@main
