name: promote images

on:
  push:
    paths:
      - images/config.yaml
      - .github/workflows/image-promotion.yml
      - .github/workflows/reusable-image-promotion.yml
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  id-token: write
  packages: write

jobs:
  promote:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-image-promotion.yml@main
    with:
      configLiteral: |
        - name: coolest-serverless-app
          dmap:
            "sha256:8246383b7fd0ca87cbac28e6b99d84cda5487f0e80d2c93f16c2f42366160a40": ["v0", "v1", "v2"]
            "sha256:0cddd0ea1bbb81f5f9f27f8a6fe37d71a5a86fd708387e111107256d4fef7f42": ["2023-04-24", "v0.0.2"]
        - name: mission-critical-service
          dmap:
            "sha256:a479f33cb7f5fe7d5149de44848bcbc38d5f107d7b47a962df7749259eef49eb": ["v1"]
            "sha256:84f35de222e8a598dcb8c4cd6ad60df93360a020c6a0647c2500735683d01944": ["2023-04-24", "v0.0.2"]
        - name: webthingy
          dmap:
            "sha256:efdb4ab576f4028e8319733890af8e7c49eed7f43bfe33e078052a1d0763ef89": ["v1"]
            "sha256:f0f843ca0c2b55210555af3f929b3d6ecd156485acc6eaefa59f6f11468b6061": ["2023-04-24", "v0.0.2"]
