name: promote images

on:
  push:
    branches:
      - main
      - master
      - canon
    paths:
      - images/config.yaml
      - .github/workflows/image-promotion.yml
      - .github/workflows/reusable-image-promotion.yml
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch: {}

permissions:
  id-token: write
  packages: write

jobs:
  promote:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-image-promotion.yml@main
    with:
      configPath: ./images/config.yaml
