name: reusable go test
on:
  workflow_call: {}
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: test
        id: test
        run: |
          go test -v -coverprofile /tmp/coverage.out -cover ./...
      - name: create coverage html
        id: coverage-html
        run: |
          go tool cover -html=/tmp/coverage.out -o /tmp/coverage.html
      - name: Upload test log
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: always()
        with:
          name: test-results
          path: |
            /tmp/coverage.out
            /tmp/coverage.html
          if-no-files-found: error
