name: golangci lint
on:
  workflow_call:
    inputs:
      config:
        type: string
        default: false
        description: |
          a .golangci.yml configuration file.
          Warning: setting this field will override an existing config
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: run-info
        name: collect job run info
        run: |
          echo "go-version=$(go list -f {{.GoVersion}} -m)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.run-info.outputs.go-version }}
          cache: false
      - name: write .golangci.yml
        if: ${{ inputs.config != null }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
