name: reusable release please
on:
  workflow_call:
    inputs:
      release-type:
        type: string
        default: go
    outputs:
      releases_created:
        value: ${{ jobs.release-please.outputs.releases_created }}
      tag:
        value: ${{ jobs.release-please.outputs.tag_name }}
      upload_url:
        value: ${{ jobs.release-please.outputs.upload_url }}
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
      upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        id: release-please
        with:
          release-type: ${{ inputs.release-type }}
          package-name: release-please-action
