name: reusable golangci lint
on:
  workflow_call: {}
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - id: run-info
        name: collect job run info
        run: |
          version="$(echo ${{ steps.setup-go.outputs.go-version }} | grep -eo --color=never '([0-9].[0-9]{2})')"
          echo "go-version=$version" >> $github_output
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.run-info.outputs.go-version }}
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
