name: reusable go container apps
on:
  workflow_call:
    inputs:
      registryOverride:
        required: false
        type: string
        description: |
          a container registry to use instead of ghcr.io.
          e.g:
            - quay.io
            - registry.gitlab.com/somecoolproject
            - ghcr.io/somecoolproject/thing
      paths:
        required: false
        type: string
        description: |
          the Go entrypoint paths for applications, where there they have `package main`
          e.g: ./cmd/thing1 ./cmd/thing2
      imagePromotionConfigLiteral:
        required: false
        type: string
        description: |
          in-line configuration for image promotion.

          e.g:
          - name: coolest-serverless-app
            dmap:
              "sha256:8246383b7fd0ca87cbac28e6b99d84cda5487f0e80d2c93f16c2f42366160a40": ["v1", "v2"]
          - name: mission-critical-service
            dmap:
              "sha256:a479f33cb7f5fe7d5149de44848bcbc38d5f107d7b47a962df7749259eef49eb": ["v1"]
          - name: webthingy
            dmap:
              "sha256:efdb4ab576f4028e8319733890af8e7c49eed7f43bfe33e078052a1d0763ef89": ["v1"]
      imagePromotionConfigPath:
        required: false
        type: string
        default: images/config.yaml
        description: |
          the local relative path to a promotion config.
          e.g: ./images/config.yaml

          the format of the file must be

          type Image struct {
            Name string              `json:"name"`
            Dmap map[string][]string `json:"dmap"`
          }

          example like

          - name: coolest-serverless-app
            dmap:
              "sha256:8246383b7fd0ca87cbac28e6b99d84cda5487f0e80d2c93f16c2f42366160a40": ["v1", "v2"]
          - name: mission-critical-service
            dmap:
              "sha256:a479f33cb7f5fe7d5149de44848bcbc38d5f107d7b47a962df7749259eef49eb": ["v1"]
          - name: webthingy
            dmap:
              "sha256:efdb4ab576f4028e8319733890af8e7c49eed7f43bfe33e078052a1d0763ef89": ["v1"]
      updateGoVersionAutoMerge:
        type: boolean
        default: false
        required: false
        description: |
          specifies whether to auto merge PRs for Go version updates to go.mod files
      containerScanningEnabled:
        type: boolean
        default: false
        required: false
        description: |
          specifies whether to enable container scanning for each image built
      containerBuildEnabled:
        type: boolean
        default: ${{ github.ref == 'refs/heads/main' || contains(fromJSON('["workflow_call", "release"]'), github.event_name) }}
        required: false
        description: |
          specifies whether to enable container builds. Defaults to on the main branch, workflow_call or release
      releaseManagementEnabled:
        type: boolean
        default: true
        required: false
        description: |
          specifies whether to enable automatic git release management
    outputs:
      images:
        value: ${{ jobs.build.outputs.images }}
jobs:
  go-build:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-go-build-smoke-test.yml@main
    with:
      paths: ${{ inputs.paths }}
  build:
    if: ${{ contains(fromJSON('["workflow_call", "push", "release"]'), github.event_name) && inputs.containerBuildEnabled }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-ko-build.yml@main
    with:
      registryOverride: ${{ inputs.registryOverride }}
      paths: ${{ inputs.paths }}
  scan:
    if: ${{ contains(fromJSON('["workflow_call", "push", "release"]'), github.event_name) && inputs.containerScanningEnabled }}
    needs: build
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-container-image-scan.yml@main
    with:
      imageRefs: ${{ needs.build.outputs.images }}
  gofmt:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-gofmt.yml@main
  golangci-lint:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-golangci-lint.yml@main
  go-test:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-go-test.yml@main
  go-vet:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-go-vet.yml@main
  govulncheck:
    if: ${{ contains(fromJSON('["workflow_call", "push", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-govulncheck.yml@main
  image-promotion-in-config-on-release:
    needs: build
    if: ${{ contains(fromJSON('["workflow_call", "release"]'), github.event_name) && inputs.imagePromotionConfigLiteral == null }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-container-image-promotion.yml@main
    with:
      configPath: ${{ inputs.imagePromotionConfigPath }}
      imageRefs: ${{ needs.build.outputs.images }}
  image-promotion:
    if: ${{ contains(fromJSON('["workflow_call", "push", "schedule"]'), github.event_name) && github.ref == 'refs/heads/main' }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-container-image-promotion.yml@main
    with:
      registryOverride: ${{ inputs.registryOverride }}
      configPath: ${{ inputs.imagePromotionConfigPath }}
      configLiteral: ${{ inputs.imagePromotionConfigLiteral }}
  update-go-version:
    if: ${{ contains(fromJSON('["workflow_call", "schedule"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-update-go-version.yml@main
    with:
      autoMerge: ${{ inputs.updateGoVersionAutoMerge }}
  presubmit-go-mod-vendor:
    if: ${{ contains(fromJSON('["workflow_call", "pull_request"]'), github.event_name) }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-presubmit-go-mod-vendor.yml@main
  release-please:
    if: ${{ contains(fromJSON('["workflow_call", "push"]'), github.event_name) && github.ref == 'refs/heads/main' }}
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-release-please.yml@main
