name: golangci lint
on:
  workflow_call: {}
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - id: run-info
        name: collect job run info
        run: |
          echo "go-version=$(go list -f {{.GoVersion}} -m)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.run-info.outputs.go-version }}
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
