name: stale
on:
  schedule:
  - cron: '0 1 * * *'
  workflow_dispatch: {}
  issue_comment: {}
jobs:
  stale:
    uses: .github/workflows/reusable-stale-submission.yml
    with:
      days-before-stale: 1
      days-before-close: 2
