name: update-go-version

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * MON"

permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-go-version:
    uses: BobyMCbobs/sample-ko-monorepo/.github/workflows/reusable-update-go-version.yml@main
